/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pawparadise1;

/**
 *
 * @author Alejandro
 */
public class PaginaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaginaInicial.class.getName());

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registrar = new javax.swing.JButton();
        Adoptar = new javax.swing.JButton();
        Donar = new javax.swing.JButton();
        Logo2 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registrar.setBackground(new java.awt.Color(255, 204, 204));
        Registrar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 36)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setText("REGISTRAR");
        Registrar.setAutoscrolls(true);
        Registrar.setBorderPainted(false);
        Registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Registrar.setFocusPainted(false);
        Registrar.setMargin(new java.awt.Insets(5, 10, 3, 14));
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarMouseClicked(evt);
            }
        });
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 240, 60));

        Adoptar.setBackground(new java.awt.Color(255, 204, 204));
        Adoptar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 36)); // NOI18N
        Adoptar.setForeground(new java.awt.Color(255, 255, 255));
        Adoptar.setText("ADOPTAR");
        Adoptar.setAutoscrolls(true);
        Adoptar.setBorderPainted(false);
        Adoptar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Adoptar.setFocusPainted(false);
        Adoptar.setMargin(new java.awt.Insets(5, 10, 3, 14));
        Adoptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdoptarMouseClicked(evt);
            }
        });
        Adoptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdoptarActionPerformed(evt);
            }
        });
        getContentPane().add(Adoptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 240, 60));

        Donar.setBackground(new java.awt.Color(255, 204, 204));
        Donar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 36)); // NOI18N
        Donar.setForeground(new java.awt.Color(255, 255, 255));
        Donar.setText("DONAR");
        Donar.setAutoscrolls(true);
        Donar.setBorderPainted(false);
        Donar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Donar.setFocusPainted(false);
        Donar.setMargin(new java.awt.Insets(5, 10, 3, 14));
        Donar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonarMouseClicked(evt);
            }
        });
        Donar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonarActionPerformed(evt);
            }
        });
        getContentPane().add(Donar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 240, 60));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMediano.png"))); // NOI18N
        getContentPane().add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 230, 240));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPI.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 920, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarMouseClicked

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
    Registrar RG = new Registrar();
            RG.setVisible(true);
            dispose();    
    }//GEN-LAST:event_RegistrarActionPerformed

    private void AdoptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdoptarMouseClicked
         // TODO add your handling code here:
    }//GEN-LAST:event_AdoptarMouseClicked

    private void AdoptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdoptarActionPerformed
     Adoptar AD = new Adoptar();
            AD.setVisible(true);
            dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_AdoptarActionPerformed

    private void DonarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DonarMouseClicked

    private void DonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonarActionPerformed
    Donar DN = new Donar();
            DN.setVisible(true);
            dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_DonarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PaginaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adoptar;
    private javax.swing.JButton Donar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo2;
    private javax.swing.JButton Registrar;
    // End of variables declaration//GEN-END:variables
}
