/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pawparadise1;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;



/**
 *
 * @author Alejandro
 */
public class Registrar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registrar.class.getName());

    /**
     * Creates new form PaginaInicial
     */
    public Registrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Jtiempo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Jvacunas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        JHisotria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxEsterilizado = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Jsexo1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Jedad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jraza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Jnombres = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Jid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        SubirFoto = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnEnviarBD1 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jtiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtiempoActionPerformed(evt);
            }
        });
        jPanel1.add(Jtiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 950, 700, 110));

        jLabel11.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel11.setText("Ingresa el nombre de las vacunas que tiene:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1070, -1, -1));

        Jvacunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JvacunasActionPerformed(evt);
            }
        });
        jPanel1.add(Jvacunas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1120, 710, 70));

        jLabel10.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel10.setText("Hace cuanto tiempo esta contigo y porque quieres darlo en adopción: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 900, -1, -1));
        jPanel1.add(JHisotria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 740, 690, 120));

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel2.setText("Cuentanos un poco de su historia y cómo conociste a este peludito:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, -1, -1));

        jComboBoxEsterilizado.setBackground(new java.awt.Color(255, 204, 204));
        jComboBoxEsterilizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBoxEsterilizado.setForeground(new java.awt.Color(255, 255, 255));
        jComboBoxEsterilizado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));
        jPanel1.add(jComboBoxEsterilizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 340, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel5.setText("Se encuentra esterilizado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, -1));

        Jsexo1.setBackground(new java.awt.Color(255, 204, 204));
        Jsexo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Jsexo1.setForeground(new java.awt.Color(255, 255, 255));
        Jsexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        Jsexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jsexo1ActionPerformed(evt);
            }
        });
        jPanel1.add(Jsexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 330, -1));

        jLabel9.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel9.setText("Sexo:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, -1, -1));

        Jedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JedadActionPerformed(evt);
            }
        });
        jPanel1.add(Jedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 320, -1));

        jLabel8.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel8.setText("Edad o un aproximado en meses:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, -1));
        jPanel1.add(Jraza, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 330, -1));

        jLabel7.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel7.setText("Raza (si la sabes) :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, -1, -1));
        jPanel1.add(Jnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 330, -1));

        jLabel12.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel12.setText("Nombre del Peludito:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));
        jPanel1.add(Jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 330, -1));

        jLabel13.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel13.setText("ID");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 230, 60));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoMediano.png"))); // NOI18N
        jPanel1.add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, -10, 230, 240));

        SubirFoto.setBackground(new java.awt.Color(255, 204, 204));
        SubirFoto.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 24)); // NOI18N
        SubirFoto.setForeground(new java.awt.Color(255, 255, 255));
        SubirFoto.setText("SUBIR FOTO");
        SubirFoto.setAutoscrolls(true);
        SubirFoto.setBorderPainted(false);
        SubirFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SubirFoto.setMargin(new java.awt.Insets(5, 10, 3, 14));
        SubirFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubirFotoMouseClicked(evt);
            }
        });
        SubirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubirFotoActionPerformed(evt);
            }
        });
        jPanel1.add(SubirFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 1310, -1, -1));

        lblFoto.setBackground(new java.awt.Color(255, 204, 204));
        lblFoto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFoto.setText("      Adjunta la foto del peludito aquí");
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1220, -1, 200));

        btnRegresar.setBackground(new java.awt.Color(255, 204, 204));
        btnRegresar.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 36)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setAutoscrolls(true);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegresar.setMargin(new java.awt.Insets(5, 10, 3, 14));
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1520, -1, -1));

        btnEnviarBD1.setBackground(new java.awt.Color(255, 204, 204));
        btnEnviarBD1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 3, 36)); // NOI18N
        btnEnviarBD1.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarBD1.setText("REGISTRAR");
        btnEnviarBD1.setAutoscrolls(true);
        btnEnviarBD1.setBorderPainted(false);
        btnEnviarBD1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEnviarBD1.setMargin(new java.awt.Insets(5, 10, 3, 14));
        btnEnviarBD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarBD1MouseClicked(evt);
            }
        });
        btnEnviarBD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarBD1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarBD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 1520, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoPI.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 1110, 1860));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 1070, 1240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JedadActionPerformed

    private void Jsexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jsexo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jsexo1ActionPerformed

    private void JtiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtiempoActionPerformed

    private void JvacunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JvacunasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JvacunasActionPerformed

    private void SubirFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubirFotoMouseClicked

    }//GEN-LAST:event_SubirFotoMouseClicked

    private void SubirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubirFotoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona una imagen");

        // Solo permite imágenes
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.addChoosableFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg", "gif"));

        int seleccion = fileChooser.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath();

            // Escalar la imagen al tamaño del JLabel
            ImageIcon imagenOriginal = new ImageIcon(ruta);
            Image imagenEscalada = imagenOriginal.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH);

            lblFoto.setIcon(new ImageIcon(imagenEscalada));
            lblFoto.setText("");

        }
    }//GEN-LAST:event_SubirFotoActionPerformed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
    

    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       PaginaInicial paginaInicial = new PaginaInicial();
    
        // Mostrar la página inicial
        paginaInicial.setVisible(true);
    
        // Cerrar la ventana actual (Registrar)
        this.dispose();
        
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEnviarBD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarBD1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarBD1MouseClicked

    private void btnEnviarBD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarBD1ActionPerformed
    Conexion con = new Conexion("pawparadise");
        Connection conn = con.conectar();

        if (conn != null) {
            try {
                String sql = "INSERT INTO mascotas (id,nombre, raza, edad, sexo, esterilizado, historia, tiempo, vacunas) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);

                // Recolectar datos de los campos
                ps.setString(1, Jid.getText());
                ps.setString(2, Jnombres.getText());
                ps.setString(3, Jraza.getText());
                ps.setString(4, Jedad.getText());
                ps.setString(5, Jsexo1.getSelectedItem().toString());
                ps.setString(6, jComboBoxEsterilizado.getSelectedItem().toString());
                ps.setString(7, JHisotria.getText());
                ps.setString(8, Jtiempo.getText());
                ps.setString(9, Jvacunas.getText());

                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Peludito registrado con éxito 🐾");

                // Limpiar campos

                Jid.setText("");
                Jnombres.setText("");
                Jraza.setText("");
                Jedad.setText("");
                Jsexo1.setSelectedIndex(0);
                jComboBoxEsterilizado.setSelectedIndex(0);
                JHisotria.setText("");
                Jtiempo.setText("");
                Jvacunas.setText("");
                lblFoto.setIcon(null);
                lblFoto.setText("      Adjunta la foto del peludito aquí");

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al guardar: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo conectar con la base de datos.");
        }
    }//GEN-LAST:event_btnEnviarBD1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registrar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField JHisotria;
    private javax.swing.JTextField Jedad;
    private javax.swing.JTextField Jid;
    private javax.swing.JTextField Jnombres;
    private javax.swing.JTextField Jraza;
    private javax.swing.JComboBox<String> Jsexo1;
    private javax.swing.JTextField Jtiempo;
    private javax.swing.JTextField Jvacunas;
    private javax.swing.JLabel Logo2;
    private javax.swing.JButton SubirFoto;
    private javax.swing.JButton btnEnviarBD1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> jComboBoxEsterilizado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    // End of variables declaration//GEN-END:variables
}
