name: Ejecutar app Java (Ant)

on:
  push:
  workflow_dispatch:   # permite correrlo manualmente

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
            java-version: '22'
            distribution: 'temurin'


      # (Por si no estuviera instalado Ant en el runner)
      - name: Install Ant
        run: sudo apt-get update && sudo apt-get install -y ant

      - name: Build with Ant
        run: ant -noinput -buildfile PawParadise2/build.xml

      - name: Run application
        run: java -jar dist/*.jar
